### ISSUE TITLE
Support for component blocks in Requirement DL syntax

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#249]
Currently, component blocks (like *part*, *test-purpose*, *test-method*, *conditions*, etc.) are not supported in DL syntax.
This is a reminder to do so.
In my opinion, we should support this [feature](https://github.com/metanorma/metanorma-ogc/issues/247) as well.
Thanks!

**Comment by opoudjis** [comment]
Extend requirement dl syntax to model, obligation, type (attributes in XML).

**Comment by opoudjis** [comment]
To get this to work, you will need to pull branch fix/reqt-dl-attrs  from metanorma-ogc and the latest standoc from github.

**Comment by manuel489** [comment]
> To get this to work, you will need to pull branch fix/reqt-dl-attrs from metanorma-ogc and the latest standoc from github.

@opoudjis, I get compilation failure when I do this.

````
...
C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/isodoc-1.7.4/lib/isodoc/css.rb:78:in `require': cannot load such file -- sassc (LoadError)
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/isodoc-1.7.4/lib/isodoc/css.rb:78:in `convert_scss'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/isodoc-1.7.4/lib/isodoc/css.rb:100:in `generate_css'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/isodoc-1.7.4/lib/isodoc/css.rb:28:in `populate_css'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/isodoc-1.7.4/lib/isodoc/html_function/html.rb:10:in `block (2 levels) in convert1'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/nokogiri-1.11.7-x64-mingw32/lib/nokogiri/xml/builder.rb:395:in `insert'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/nokogiri-1.11.7-x64-mingw32/lib/nokogiri/xml/builder.rb:378:in `method_missing'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/isodoc-1.7.4/lib/isodoc/html_function/html.rb:8:in `block in convert1'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/nokogiri-1.11.7-x64-mingw32/lib/nokogiri/xml/builder.rb:296:in `initialize'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/nokogiri-1.11.7-x64-mingw32/lib/nokogiri/xml/builder.rb:255:in `new'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/nokogiri-1.11.7-x64-mingw32/lib/nokogiri/xml/builder.rb:255:in `with'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/isodoc-1.7.4/lib/isodoc/function/utils.rb:33:in `noko'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/isodoc-1.7.4/lib/isodoc/html_function/html.rb:7:in `convert1'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/isodoc-1.7.4/lib/isodoc/convert.rb:165:in `convert'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/isodoc-1.7.4/lib/isodoc/html_convert.rb:26:in `convert'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/bundler/gems/metanorma-ogc-255fc68cbb33/lib/metanorma/ogc/processor.rb:45:in `output'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-1.3.10/lib/metanorma/compile.rb:219:in `block in process_extensions'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-1.3.10/lib/metanorma/compile.rb:206:in `each'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-1.3.10/lib/metanorma/compile.rb:206:in `process_extensions'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-1.3.10/lib/metanorma/compile.rb:35:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.15/lib/metanorma/cli/compiler.rb:45:in `compile_file'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.15/lib/metanorma/cli/compiler.rb:30:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.15/lib/metanorma/cli/compiler.rb:35:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.15/lib/metanorma/cli/command.rb:210:in `compile_document'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.15/lib/metanorma/cli/command.rb:45:in `block in compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.15/lib/metanorma/cli/command.rb:45:in `each'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.15/lib/metanorma/cli/command.rb:45:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-hollaback-0.2.0/lib/thor/hollaback.rb:62:in `run'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.15/lib/metanorma/cli.rb:34:in `start'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.15/exe/metanorma:22:in `block in <top (required)>'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.15/exe/metanorma:40:in `<top (required)>'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/bin/metanorma:23:in `load'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/bin/metanorma:23:in `<main>'
````

**Comment by manuel489** [comment]
Pending support for *description* paragraphs

**Comment by opoudjis** [comment]
also requirement, permission, recommendation

**Comment by opoudjis** [comment]
Reference has been sprung as a component type. I would dispute its necessity, but I'm past caring.
