### ISSUE TITLE
Compilation failure on Requirement DL syntax

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#258]
Apparently, the presence of a paragraph is necessary in DL syntax in order to succeed on building the document.

For example:
````
[[rc_ade]]
[requirement]
====
[%metadata]
model:: ogc
type:: class
label:: http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-ade
subject:: Conceptual Model
inherit:: <<rc_core,/req/req-class-core>>

This paragraph is necessary so that no build failure occurs.
====
````

If there is no paragraph, an error message is shown:
````
...
Crossreferences: (XML Line 000517): OMGMDA does not have a corresponding anchor ID in the bibliography!
AsciiDoc Input: (XML Line 000417): Error: Term reference in `term[standardization-target]` missing:                 "standardization-target" is not defined in document
C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/nokogiri-1.11.7-x64-mingw32/lib/nokogiri/xml/node.rb:1183:in `add_sibling': Cannot add sibling to a node with no parent (RuntimeError)
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/nokogiri-1.11.7-x64-mingw32/lib/nokogiri/xml/node.rb:189:in `add_previous_sibling'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/nokogiri-1.11.7-x64-mingw32/lib/nokogiri/xml/node.rb:213:in `before'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-standoc-1.10.4.1/lib/asciidoctor/standoc/cleanup_reqt.rb:28:in `block (2 levels) in requirement_descriptions'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/nokogiri-1.11.7-x64-mingw32/lib/nokogiri/xml/node_set.rb:239:in `block in each'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/nokogiri-1.11.7-x64-mingw32/lib/nokogiri/xml/node_set.rb:238:in `upto'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/nokogiri-1.11.7-x64-mingw32/lib/nokogiri/xml/node_set.rb:238:in `each'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-standoc-1.10.4.1/lib/asciidoctor/standoc/cleanup_reqt.rb:24:in `block in requirement_descriptions'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/nokogiri-1.11.7-x64-mingw32/lib/nokogiri/xml/node_set.rb:239:in `block in each'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/nokogiri-1.11.7-x64-mingw32/lib/nokogiri/xml/node_set.rb:238:in `upto'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/nokogiri-1.11.7-x64-mingw32/lib/nokogiri/xml/node_set.rb:238:in `each'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-standoc-1.10.4.1/lib/asciidoctor/standoc/cleanup_reqt.rb:23:in `requirement_descriptions'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-standoc-1.10.4.1/lib/asciidoctor/standoc/cleanup_reqt.rb:6:in `requirement_cleanup'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-standoc-1.10.4.1/lib/asciidoctor/standoc/cleanup.rb:61:in `cleanup'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-standoc-1.10.4.1/lib/asciidoctor/standoc/base.rb:206:in `makexml'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-ogc-1.4.0/lib/asciidoctor/ogc/converter.rb:24:in `makexml'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-standoc-1.10.4.1/lib/asciidoctor/standoc/base.rb:171:in `document'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-standoc-1.10.4.1/lib/asciidoctor/standoc/utils.rb:13:in `convert'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/asciidoctor-2.0.16/lib/asciidoctor/document.rb:948:in `convert'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/asciidoctor-2.0.16/lib/asciidoctor/convert.rb:120:in `convert'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-1.3.9.1/lib/metanorma/input/asciidoc.rb:18:in `process'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-1.3.9.1/lib/metanorma/processor.rb:21:in `input_to_isodoc'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-1.3.9.1/lib/metanorma/compile.rb:107:in `process_input_adoc'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-1.3.9.1/lib/metanorma/compile.rb:90:in `process_input'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-1.3.9.1/lib/metanorma/compile.rb:30:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.14/lib/metanorma/cli/compiler.rb:45:in `compile_file'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.14/lib/metanorma/cli/compiler.rb:30:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.14/lib/metanorma/cli/compiler.rb:35:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.14/lib/metanorma/cli/command.rb:210:in `compile_document'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.14/lib/metanorma/cli/command.rb:45:in `block in compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.14/lib/metanorma/cli/command.rb:45:in `each'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.14/lib/metanorma/cli/command.rb:45:in `compile'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-hollaback-0.2.0/lib/thor/hollaback.rb:62:in `run'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.14/lib/metanorma/cli.rb:34:in `start'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.14/exe/metanorma:22:in `block in <top (required)>'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/gems/metanorma-cli-1.4.14/exe/metanorma:40:in `<top (required)>'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/bin/metanorma:23:in `load'
        from C:/tools/ruby25/lib/ruby/gems/2.5.0/ruby/2.5.0/bin/metanorma:23:in `<main>'
````

**Comment by ronaldtse** [comment]
Off the topic but one of the errors you see:
> AsciiDoc Input: (XML Line 000417): Error: Term reference in `term[standardization-target]` missing:                 "standardization-target" is not defined in document

Is due to https://github.com/metanorma/metanorma-ogc/issues/245. I hope that will go away by the next release.

**Comment by ronaldtse** [comment]
This issue also relates to https://github.com/metanorma/metanorma-ogc/issues/249

**Comment by opoudjis** [comment]
Error already resolved in https://github.com/metanorma/metanorma-standoc/commit/dba32c08bd873de215a48a9ad9172ed2bf833c7b#diff-af345eab25eeccd75e5fc06b57f4454ab32921d3127ca517d069172c11ada5dd
