### ISSUE TITLE
Fix specs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#26]
The following specs are failing

```ruby

Failures:
  1) Asciidoctor::Ogc converts a blank document
     Failure/Error:
       def insert_toc(intro, docxml, level)
         toc = ""
         toc += make_WordToC(docxml, level)
         if docxml.at("//p[@class = 'TableTitle']")
           toc += %{<p class="TOCTitle">List of Tables</p>}
           toc += make_TableWordToC(docxml)
         end
         if docxml.at("//p[@class = 'FigureTitle']")
           toc += %{<p class="TOCTitle">List of Figures</p>}
           toc += make_FigureWordToC(docxml)
     
     ArgumentError:
       wrong number of arguments (given 2, expected 3)
     # ./lib/isodoc/ogc/word_convert.rb:61:in `insert_toc'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:122:in `word_intro'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:106:in `word_preface'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:58:in `word_cleanup'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:43:in `toWord'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:37:in `postprocess'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/convert.rb:154:in `convert'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_convert.rb:34:in `convert'
     # ./lib/asciidoctor/ogc/converter.rb:58:in `document'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/utils.rb:96:in `convert'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1190:in `convert'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1521:in `convert'
     # ./spec/asciidoctor/base_spec.rb:44:in `block (2 levels) in <top (required)>'
  2) Asciidoctor::Ogc uses default fonts
     Failure/Error:
       def insert_toc(intro, docxml, level)
         toc = ""
         toc += make_WordToC(docxml, level)
         if docxml.at("//p[@class = 'TableTitle']")
           toc += %{<p class="TOCTitle">List of Tables</p>}
           toc += make_TableWordToC(docxml)
         end
         if docxml.at("//p[@class = 'FigureTitle']")
           toc += %{<p class="TOCTitle">List of Figures</p>}
           toc += make_FigureWordToC(docxml)
     
     ArgumentError:
       wrong number of arguments (given 2, expected 3)
     # ./lib/isodoc/ogc/word_convert.rb:61:in `insert_toc'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:122:in `word_intro'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:106:in `word_preface'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:58:in `word_cleanup'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:43:in `toWord'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:37:in `postprocess'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/convert.rb:154:in `convert'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_convert.rb:34:in `convert'
     # ./lib/asciidoctor/ogc/converter.rb:58:in `document'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/utils.rb:96:in `convert'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1190:in `convert'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1521:in `convert'
     # ./spec/asciidoctor/base_spec.rb:425:in `block (2 levels) in <top (required)>'
  3) Asciidoctor::Ogc uses Chinese fonts
     Failure/Error:
       def insert_toc(intro, docxml, level)
         toc = ""
         toc += make_WordToC(docxml, level)
         if docxml.at("//p[@class = 'TableTitle']")
           toc += %{<p class="TOCTitle">List of Tables</p>}
           toc += make_TableWordToC(docxml)
         end
         if docxml.at("//p[@class = 'FigureTitle']")
           toc += %{<p class="TOCTitle">List of Figures</p>}
           toc += make_FigureWordToC(docxml)
     
     ArgumentError:
       wrong number of arguments (given 2, expected 3)
     # ./lib/isodoc/ogc/word_convert.rb:61:in `insert_toc'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:122:in `word_intro'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:106:in `word_preface'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:58:in `word_cleanup'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:43:in `toWord'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:37:in `postprocess'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/convert.rb:154:in `convert'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_convert.rb:34:in `convert'
     # ./lib/asciidoctor/ogc/converter.rb:58:in `document'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/utils.rb:96:in `convert'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1190:in `convert'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1521:in `convert'
     # ./spec/asciidoctor/base_spec.rb:443:in `block (2 levels) in <top (required)>'
  4) Asciidoctor::Ogc uses specified fonts
     Failure/Error:
       def insert_toc(intro, docxml, level)
         toc = ""
         toc += make_WordToC(docxml, level)
         if docxml.at("//p[@class = 'TableTitle']")
           toc += %{<p class="TOCTitle">List of Tables</p>}
           toc += make_TableWordToC(docxml)
         end
         if docxml.at("//p[@class = 'FigureTitle']")
           toc += %{<p class="TOCTitle">List of Figures</p>}
           toc += make_FigureWordToC(docxml)
     
     ArgumentError:
       wrong number of arguments (given 2, expected 3)
     # ./lib/isodoc/ogc/word_convert.rb:61:in `insert_toc'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:122:in `word_intro'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:106:in `word_preface'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:58:in `word_cleanup'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:43:in `toWord'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_function/postprocess.rb:37:in `postprocess'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/convert.rb:154:in `convert'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/isodoc-0.9.19/lib/isodoc/word_convert.rb:34:in `convert'
     # ./lib/asciidoctor/ogc/converter.rb:58:in `document'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/metanorma-standoc-1.1.5/lib/asciidoctor/standoc/utils.rb:96:in `convert'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/asciidoctor-1.5.8/lib/asciidoctor/document.rb:1190:in `convert'
     # /home/travis/.rvm/gems/ruby-2.5.4/gems/asciidoctor-1.5.8/lib/asciidoctor.rb:1521:in `convert'
     # ./spec/asciidoctor/base_spec.rb:464:in `block (2 levels) in <top (required)>'
  5) Asciidoctor::Ogc uses user-specified Word stylesheets
     Failure/Error: html = File.read("spec/assets/test.doc", encoding: "utf-8")
     
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - spec/assets/test.doc
     # ./spec/asciidoctor/base_spec.rb:524:in `read'
     # ./spec/asciidoctor/base_spec.rb:524:in `block (2 levels) in <top (required)>'
  6) IsoDoc::Ogc injects JS into blank html
     Failure/Error:
       def insert_toc(intro, docxml, level)
         toc = ""
         toc += make_WordToC(docxml, level)
         if docxml.at("//p[@class = 'TableTitle']")
           toc += %{<p class="TOCTitle">List of Tables</p>}
           toc += make_TableWordToC(docxml)
         end
         if docxml.at("//p[@class = 'FigureTitle']")
           toc += %{<p class="TOCTitle">List of Figures</p>}
           toc += make_FigureWordToC(docxml)
     
     ArgumentError:
       wrong number of arguments (given 2, expected 3)
     # ./lib/isodoc/ogc/word_convert.rb:61:in `insert_toc'

```

**Comment by opoudjis** [comment]
In future, @ronaldtse, do not raise issues like this: they clog up my backlog for no good reason. Gems have dependencies, gem specs will break when an upstream gem changes (often due to necessary refactoring) until there is a release, there is a release every week or two. metanorma-ogc rspec works fine locally, which means this will go away when I rerelease isodoc.

**Comment by ronaldtse** [comment]
Sure, but we ought to find a way not to have failing specs due to dependencies. The master branch should always pass.
