### ISSUE TITLE
Support `step` components in DL syntax

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-ogc#278]
Markup sample:
```adoc

[requirement]
====
[%metadata]
type:: abstracttest
label:: /conf/core/landingpage-success
subject:: <<req_core_landingpage-success,/req/core/landingpage-success>>
test-purpose:: Validate that the landing page complies with the require structure and contents.

[.component,class=test method type]
--
Manual Inspection
--

[.component,class=test method]
=====
[.component,class=step]
--
Validate that a document was returned with an HTTP status code or 200.
--

[.component,class=step]
--
Validate the landing page for all supported media types using the resources and tests identified in <<landing-page-schema>>
--

[.component,class=step]
======
For formats that require manual inspection, perform the following:

[.component,class=step]
--
Validate that the landing page includes a "service-desc" and/or "service-doc" link to an API Definition.
--

[.component,class=step]
--
Validate that the landing page includes a "http://www.opengis.net/def/rel/ogc/1.0/conformance" link to the conformance class declaration.
--

[.component,class=step]
--
Validate that the landing page includes a "processes" link to the list of processes.
--
======
=====
```

We need to support `test method type`, `test method`, and `step` attributes in DL syntax.

**Comment by opoudjis** [comment]
Officially these are test-method, test-method-type, but I'm allowing them to be recognised with spaces.

**Comment by opoudjis** [comment]
We now support nested definition lists in the syntax. So the foregoing is to be rendered as:

````
[requirement]
====
[%metadata]
type:: abstracttest
label:: /conf/core/landingpage-success
subject:: <<req_core_landingpage-success,/req/core/landingpage-success>>
test-purpose:: Validate that the landing page complies with the require structure and contents.
test-method-type: Manual Inspection
test-method::
step::: Validate that a document was returned with an HTTP status code or 200.
step::: Validate the landing page for all supported media types using the resources and tests identified in <<landing-page-schema>>
step::: For formats that require manual inspection, perform the following:
step:::: Validate that the landing page includes a "service-desc" and/or "service-doc" link to an API Definition.
step:::: Validate that the landing page includes a "http://www.opengis.net/def/rel/ogc/1.0/conformance" link to the conformance class declaration.
step:::: Validate that the landing page includes a "processes" link to the list of processes.
=====
````

**Comment by opoudjis** [comment]
Adjustment to move nested dl after any content above it:

````
step::: Step 2
step:::: Step 2a
````

as

````
* Step 2
  * Step 2a
````

Requires metanorma-standoc push

**Comment by manuel489** [comment]
@opoudjis, after the release I have updated from metanorma-cli.
I get compilation failure when trying to build:
````
[requirement]
====
[%metadata]
type:: abstracttest
label:: /conf/core/landingpage-success
subject:: <<req_core_landingpage-success,/req/core/landingpage-success>>
test-purpose:: Validate that the landing page complies with the require structure and contents.
test-method-type: Manual Inspection
test-method::
step::: Validate that a document was returned with an HTTP status code or 200.
step::: Validate the landing page for all supported media types using the resources and tests identified in <<landing-page-schema>>
step::: For formats that require manual inspection, perform the following:
step:::: Validate that the landing page includes a "service-desc" and/or "service-doc" link to an API Definition.
step:::: Validate that the landing page includes a "http://www.opengis.net/def/rel/ogc/1.0/conformance" link to the conformance class declaration.
step:::: Validate that the landing page includes a "processes" link to the list of processes.
=====
````

Part of the error message:
````
...
Metanorma XML Syntax: (XML Line 000476:13): element "component" incomplete; expected element "admonition", "bookmark", "dl", "example", "figure", "form", "formula", "hr", "imagemap", "note", "ol", "p", "pagebreak", "passthrough", "permission", "pre", "quote", "recommendation", "requirement", "review", "sourcecode", "svgmap", "table", "toc" or "ul"
Metanorma XML Syntax: (XML Line 000564:16): element "ogc-standard" incomplete; missing required element "bibliography"
no implicit conversion of String into Integer
/var/lib/gems/2.5.0/gems/metanorma-ogc-1.4.3/lib/isodoc/ogc/reqt.rb:87:in `[]'
/var/lib/gems/2.5.0/gems/metanorma-ogc-1.4.3/lib/isodoc/ogc/reqt.rb:87:in `recommendation_attributes1_component'
/var/lib/gems/2.5.0/gems/metanorma-ogc-1.4.3/lib/isodoc/ogc/reqt.rb:128:in `requirement_component_parse'
/var/lib/gems/2.5.0/gems/metanorma-ogc-1.4.3/lib/isodoc/ogc/reqt.rb:174:in `block in recommendation_parse1'
/var/lib/gems/2.5.0/gems/metanorma-ogc-1.4.3/lib/isodoc/ogc/reqt.rb:174:in `each'
/var/lib/gems/2.5.0/gems/metanorma-ogc-1.4.3/lib/isodoc/ogc/reqt.rb:174:in `recommendation_parse1'
/var/lib/gems/2.5.0/gems/metanorma-ogc-1.4.3/lib/isodoc/ogc/reqt.rb:183:in `block in recommendation_to_table'
/var/lib/gems/2.5.0/gems/nokogiri-1.12.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/var/lib/gems/2.5.0/gems/nokogiri-1.12.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `upto'
/var/lib/gems/2.5.0/gems/nokogiri-1.12.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:238:in `each'
/var/lib/gems/2.5.0/gems/metanorma-ogc-1.4.3/lib/isodoc/ogc/reqt.rb:182:in `recommendation_to_table'
/var/lib/gems/2.5.0/gems/metanorma-ogc-1.4.3/lib/isodoc/ogc/presentation_xml_convert.rb:159:in `block'
/var/lib/gems/2.5.0/gems/isodoc-1.7.6.1/lib/isodoc/presentation_xml_convert.rb:27:in `conversions'
/var/lib/gems/2.5.0/gems/isodoc-1.7.6.1/lib/isodoc/presentation_xml_convert.rb:18:in `convert1'
/var/lib/gems/2.5.0/gems/metanorma-ogc-1.4.3/lib/isodoc/ogc/presentation_xml_convert.rb:12:in `convert1'
/var/lib/gems/2.5.0/gems/isodoc-1.7.6.1/lib/isodoc/convert.rb:166:in `convert'
/var/lib/gems/2.5.0/gems/metanorma-ogc-1.4.3/lib/metanorma/ogc/processor.rb:51:in `output'
/var/lib/gems/2.5.0/gems/metanorma-1.3.11/lib/metanorma/compile.rb:222:in `block in process_extensions'
/var/lib/gems/2.5.0/gems/metanorma-1.3.11/lib/metanorma/compile.rb:206:in `each'
/var/lib/gems/2.5.0/gems/metanorma-1.3.11/lib/metanorma/compile.rb:206:in `process_extensions'
/var/lib/gems/2.5.0/gems/metanorma-1.3.11/lib/metanorma/compile.rb:35:in `compile'
/var/lib/gems/2.5.0/gems/metanorma-cli-1.4.17/lib/metanorma/cli/compiler.rb:45:in `compile_file'
/var/lib/gems/2.5.0/gems/metanorma-cli-1.4.17/lib/metanorma/cli/compiler.rb:30:in `compile'
/var/lib/gems/2.5.0/gems/metanorma-cli-1.4.17/lib/metanorma/cli/compiler.rb:35:in `compile'
/var/lib/gems/2.5.0/gems/metanorma-cli-1.4.17/lib/metanorma/cli/command.rb:210:in `compile_document'
/var/lib/gems/2.5.0/gems/metanorma-cli-1.4.17/lib/metanorma/cli/command.rb:45:in `block in compile'
/var/lib/gems/2.5.0/gems/metanorma-cli-1.4.17/lib/metanorma/cli/command.rb:45:in `each'
/var/lib/gems/2.5.0/gems/metanorma-cli-1.4.17/lib/metanorma/cli/command.rb:45:in `compile'
/var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.5.0/gems/thor-hollaback-0.2.0/lib/thor/hollaback.rb:62:in `run'
/var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
/var/lib/gems/2.5.0/gems/metanorma-cli-1.4.17/lib/metanorma/cli.rb:34:in `start'
/var/lib/gems/2.5.0/gems/metanorma-cli-1.4.17/exe/metanorma:22:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/metanorma-cli-1.4.17/exe/metanorma:40:in `<top (required)>'
/var/lib/gems/2.5.0/bin/metanorma:23:in `load'
/var/lib/gems/2.5.0/bin/metanorma:23:in `<main>'
````

**Comment by opoudjis** [comment]
Have debugged

**Comment by manuel489** [comment]
Confirmed fixed 👍
