### ISSUE TITLE
Aviation ER failing to generate PDF

### ISSUE THREAD

**Issue by gbuehler** [metanorma/metanorma-ogc#323]
The Aviation API ER is failing to generate the PDF using the pipeline in OGC Gitlab:

https://gitlab.ogc.org/ogc/T17-D002-Aviation-API-ER/-/tree/master

Although it says it completed the build, pages, and deploy successfully, there is a 0 byte PDF file.

Here is a section of the log when I run it locally (which is not displayed in the Pipeline in Gitlab):

`
java -Xss5m -Xmx2048m -jar /usr/local/bundle/gems/mn2pdf-1.38.1/lib/../bin/mn2pdf.jar --xml-file "document.presentation.xml" --xsl-file "/usr/local/bundle/gems/metanorma-ogc-1.5.3/lib/isodoc/ogc/ogc.engineering-report.xsl" --pdf-file "document.pdf" --font-manifest "/tmp/fontist_locations20211130-1-11cnpjv.yml"
[mn2pdf] Fatal: mn2pdf Preparing...
Input: XML (document.presentation.xml)
Input: XSL (/usr/local/bundle/gems/metanorma-ogc-1.5.3/lib/isodoc/ogc/ogc.engineering-report.xsl)
Output: PDF (document.pdf)

[INFO] XSL-FO file preparation...
Could not read image DPI, use default value 96 DPI
Transforming to PDF...
Default page-height set to: 11.00in
Default page-width set to: 8.50in
Rendered page #1.
The contents of fo:region-after on page ii exceed the available area in the block-progression direction by 17007 millipoints. (See position 13:400)
Rendered page #2.
javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: null:104:5421: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 104:5421)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:428)
	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:314)
	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:192)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:174)
Caused by: org.apache.fop.fo.ValidationException: null:104:5421: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 104:5421)
	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
	at com.sun.proxy.$Proxy12.missingLinkDestination(Unknown Source)
	at org.apache.fop.fo.flow.BasicLink.bind(BasicLink.java:95)
	at org.apache.fop.fo.FObj.processNode(FObj.java:131)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:293)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
	at org.apache.xalan.transformer.TransformerIdentityImpl.startElement(TransformerIdentityImpl.java:1073)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	... 4 more
---------
org.apache.fop.fo.ValidationException: null:104:5421: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 104:5421)
	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
	at com.sun.proxy.$Proxy12.missingLinkDestination(Unknown Source)
	at org.apache.fop.fo.flow.BasicLink.bind(BasicLink.java:95)
	at org.apache.fop.fo.FObj.processNode(FObj.java:131)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:293)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
	at org.apache.xalan.transformer.TransformerIdentityImpl.startElement(TransformerIdentityImpl.java:1073)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:428)
	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:314)
	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:192)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:174)
XSL-FO file for debugging saved into: /metanorma/document.pdf.fo.debug.xml
`

**Comment by ronaldtse** [comment]
Thanks @gbuehler   would it be possible to share the "document.presentation.xml" file and also the "document.pdf.fo.debug.xml" for debugging purposes?

Ping @Intelligent2013

**Comment by Intelligent2013** [comment]
I _assume_ error:
`
org.apache.fop.fo.ValidationException: null:104:5421: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified.
`
relates to ToC items in PDF. It seems some section title doesn't have (or has an empty) the attribute `id`. I'll modify OGC xslt to omit processing ToC items without `id`, but would be better to look at the source xml what's wrong in it.

**Comment by Intelligent2013** [comment]
@gbuehler thanks!

**Comment by Intelligent2013** [comment]
@ronaldtse the reason of issue in missing `id` for 1-st level section `Executive Summary`. 2nd `clause` in `preface` doesn't have `id`:
```xml
<preface>
		<abstract id="_abstract" displayorder="1">
			<title depth="1">I.<tab/>Abstract</title>
			...
			<clause id="_executive_summary" type="executivesummary" obligation="informative">
				<title depth="2">I.A.<tab/>Executive Summary</title>
				...
		</abstract>
		<clause type="executivesummary" obligation="informative" displayorder="2">
			<title depth="1">Executive Summary</title>
			...
```
XSLT uses the attributes `id` for binding ToC item with section's position on the page.
The non-empty value for internal-destination in XSL-FO is critical:
`<fo:basic-link internal-destination="{@id}"`.
Today I've added the solution to ignore this cases (https://github.com/metanorma/mn-native-pdf/commit/39c9b9e2d31432bc88f9dbee0aa20bf4bf731772) and now the PDF creates ok, but without section `II` in ToC:
![image](https://user-images.githubusercontent.com/5559926/144294934-9b649355-56df-4dbb-be92-68fc1175af9f.png)

. . .
In the document body it renders (but without number):
![image](https://user-images.githubusercontent.com/5559926/144295004-c2657dc7-a345-4395-9396-1c7e1e2743a0.png)

May be this issue occurs due  the subsection 'Executive Summary' in Abstract?

Also, there is issue with image rendering - Figure 13 doesn't showing (https://github.com/metanorma/mn-native-pdf/issues/336). I'll look what is the reason.

**Comment by gbuehler** [comment]
OK, thanks.  

changing 

`=== Executive Summary`

to

`== Executive Summary`

allows the PDF to build.

**Comment by gbuehler** [comment]
@Intelligent2013 

When I run this locally, it is figure 12 that is not built d107a-structure.png

![d107a-structure](https://user-images.githubusercontent.com/221625/144447885-088bce62-1c6b-4e04-bffd-531a817e5788.png)

**Comment by Intelligent2013** [comment]
@gbuehler for this image there is some incompatibility in Java. I'm working on this issue here: https://github.com/metanorma/mn-native-pdf/issues/336 and going to open a bug on OpenJDK tracker. Can we share the image there?

As workaround solution I propose to re-save this image with some application:
- open in Preview (Mac), and then File->Export
- open in XnView, GIMP, etc.
 to regenerate internal meta-information.

What is application did you used for this image generation?

**Comment by Intelligent2013** [comment]
@gbuehler re-saved image:
![image](https://user-images.githubusercontent.com/5559926/144469632-b68d2b6a-935d-482e-8369-51acd44032a3.png)

**Comment by gbuehler** [comment]
This new image worked. I will close this issue.  You are welcome to re-open if needed.

**Comment by ronaldtse** [comment]
@gbuehler I ran this image through `pngcheck` and it gave the following error:

```sh
$ pngcheck ~/Downloads/144447885-088bce62-1c6b-4e04-bffd-531a817e5788.png
/Users/me/Downloads/144447885-088bce62-1c6b-4e04-bffd-531a817e5788.png  invalid bKGD length
ERROR: /Users/me/Downloads/144447885-088bce62-1c6b-4e04-bffd-531a817e5788.png
```

Technically it is a broken PNG file. We should probably add an error message and a suggested solution on invalid images. Thanks!
