### ISSUE TITLE
Word crash on ER D023

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#327]
```
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/mn2pdf-1.38.1/lib/../bin/mn2pdf.jar --xml-file "/Users/me/src/ogc/T17-D022-Model-Driven-Standards-ER/site/documents/document.presentation.xml" --xsl-file "/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-ogc-1.5.3/lib/isodoc/ogc/ogc.engineering-report.xsl" --pdf-file "/Users/me/src/ogc/T17-D022-Model-Driven-Standards-ER/site/documents/document.pdf" --param baseassetpath= "/Users/me/src/ogc/T17-D022-Model-Driven-Standards-ER/sources" --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20211206-31668-qw7bu5.yml"
Is a directory - read
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1416:in `copy_stream'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1416:in `block (2 levels) in copy_file'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1415:in `open'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1415:in `block in copy_file'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1414:in `open'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1414:in `copy_file'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:514:in `copy_file'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:433:in `block in cp'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1597:in `block in fu_each_src_dest'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1613:in `fu_each_src_dest0'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1595:in `fu_each_src_dest'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:432:in `cp'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/html2doc-1.2.1/lib/html2doc/mime.rb:116:in `block in image_cleanup'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:979:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/html2doc-1.2.1/lib/html2doc/mime.rb:109:in `image_cleanup'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/html2doc-1.2.1/lib/html2doc/base.rb:56:in `cleanup'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/html2doc-1.2.1/lib/html2doc/base.rb:44:in `process_html'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/html2doc-1.2.1/lib/html2doc/base.rb:10:in `process'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-ogc-1.5.3/lib/isodoc/ogc/word_convert.rb:237:in `toWord'
```

**Comment by ronaldtse** [comment]
From https://gitlab.ogc.org/ogc/T17-D022-Model-Driven-Standards-ER

**Comment by opoudjis** [comment]
Just pulled and compiled, cannot replicate.

**Comment by ronaldtse** [comment]
Tou should be seeing another error due to PDF processing that's masking this.

**Comment by opoudjis** [comment]
I have generated the DOC, it is the PDF that's failing to generate, and that has to be followed up by @Intelligent2013 . I'm sending him the file.

**Comment by Intelligent2013** [comment]
@opoudjis  PDF generation issue was fixed a few days ago in https://github.com/metanorma/mn-native-pdf/issues/334.
I've checked - PDF generated successfully.

**Comment by ronaldtse** [comment]
Using git gems:

Gemfile:
```rb
source "https://rubygems.org"

gem "metanorma-cli"
gem "metanorma-ogc", git: "https://github.com/metanorma/metanorma-ogc"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc"
gem "mnconvert", git: "https://github.com/metanorma/mnconvert-ruby"
gem "isodoc", git: "https://github.com/metanorma/isodoc"
gem "sassc"
```

```
Metanorma XML Syntax: (XML Line 007497:21168): character content of element "from" invalid; must be a year
Metanorma XML Syntax: (XML Line 007497:22530): character content of element "from" invalid; must be a year
Metanorma XML Syntax: (XML Line 007499:29): element "docidentifier" not allowed yet; expected element "fetched", "formattedref" or "title"
Metanorma XML Syntax: (XML Line 007509:29): element "docidentifier" not allowed yet; expected element "fetched", "formattedref" or "title"
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/mn2pdf-1.38.1/lib/../bin/mn2pdf.jar --xml-file "/Users/me/src/ogc/T17-D022-Model-Driven-Standards-ER/site/documents/document.presentation.xml" --xsl-file "/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/bundler/gems/metanorma-ogc-068bca32b3ac/lib/isodoc/ogc/ogc.engineering-report.xsl" --pdf-file "/Users/me/src/ogc/T17-D022-Model-Driven-Standards-ER/site/documents/document.pdf" --param baseassetpath= "/Users/me/src/ogc/T17-D022-Model-Driven-Standards-ER/sources" --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20211206-40337-5jp1nm.yml"
Is a directory - read
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1416:in `copy_stream'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1416:in `block (2 levels) in copy_file'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1415:in `open'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1415:in `block in copy_file'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1414:in `open'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1414:in `copy_file'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:514:in `copy_file'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:433:in `block in cp'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1597:in `block in fu_each_src_dest'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1613:in `fu_each_src_dest0'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:1595:in `fu_each_src_dest'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/3.0.0/fileutils.rb:432:in `cp'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/html2doc-1.2.1/lib/html2doc/mime.rb:116:in `block in image_cleanup'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:979:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `block in traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:239:in `block in each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `upto'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node_set.rb:238:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/nokogiri-1.12.5-arm64-darwin/lib/nokogiri/xml/node.rb:978:in `traverse'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/html2doc-1.2.1/lib/html2doc/mime.rb:109:in `image_cleanup'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/html2doc-1.2.1/lib/html2doc/base.rb:56:in `cleanup'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/html2doc-1.2.1/lib/html2doc/base.rb:44:in `process_html'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/html2doc-1.2.1/lib/html2doc/base.rb:10:in `process'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/bundler/gems/metanorma-ogc-068bca32b3ac/lib/isodoc/ogc/word_convert.rb:237:in `toWord'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/bundler/gems/isodoc-a7f62a2e8498/lib/isodoc/word_function/postprocess.rb:36:in `postprocess'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/bundler/gems/isodoc-a7f62a2e8498/lib/isodoc/convert.rb:179:in `convert'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/bundler/gems/isodoc-a7f62a2e8498/lib/isodoc/word_convert.rb:20:in `convert'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/bundler/gems/metanorma-ogc-068bca32b3ac/lib/metanorma/ogc/processor.rb:47:in `output'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-1.4.2/lib/metanorma/compile.rb:225:in `block in process_extensions'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-1.4.2/lib/metanorma/compile.rb:206:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-1.4.2/lib/metanorma/compile.rb:206:in `process_extensions'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-1.4.2/lib/metanorma/compile.rb:35:in `compile'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.3/lib/metanorma/cli/compiler.rb:45:in `compile_file'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.3/lib/metanorma/cli/compiler.rb:30:in `compile'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.3/lib/metanorma/cli/compiler.rb:35:in `compile'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.3/lib/metanorma/cli/site_generator.rb:82:in `compile'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.3/lib/metanorma/cli/site_generator.rb:28:in `block in generate'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.3/lib/metanorma/cli/site_generator.rb:28:in `each'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.3/lib/metanorma/cli/site_generator.rb:28:in `generate'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.3/lib/metanorma/cli/site_generator.rb:23:in `generate'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.3/lib/metanorma/cli/commands/site.rb:25:in `generate'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.3/lib/metanorma/cli.rb:34:in `start'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.3/exe/metanorma:22:in `block in <top (required)>'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.3/exe/metanorma:40:in `<top (required)>'
/Users/me/.rbenv/versions/3.0.3/bin/metanorma:25:in `load'
/Users/me/.rbenv/versions/3.0.3/bin/metanorma:25:in `<top (required)>'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `load'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:23:in `run'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/cli.rb:478:in `exec'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/cli.rb:31:in `dispatch'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/cli.rb:25:in `start'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/exe/bundle:37:in `<top (required)>'
/Users/me/.rbenv/versions/3.0.3/bin/bundle:23:in `load'
/Users/me/.rbenv/versions/3.0.3/bin/bundle:23:in `<main>'
[info]: Building collection file: /Users/me/src/ogc/T17-D022-Model-Driven-Standards-ER/site/documents.xml ...
[info]: Generating html site in /Users/me/src/ogc/T17-D022-Model-Driven-Standards-ER/site ...
Site has been generated at /Users/me/src/ogc/T17-D022-Model-Driven-Standards-ER/site
```

**Comment by ronaldtse** [comment]
Wow. Found the culprit. It is the `inkscape` command being missing from PATH (after I migrated to M1 brew, which is at `/opt/homebrew/`). Luckily this doesn't happen on the single binary version because Inkscape is bundler.

Metanorma should immediately fail when Inkscape wasn't found because it is a hard dependency.
