### ISSUE TITLE
(URGENT) PDF: Crash in mn-samples-ogc 14-065r2

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#332]
Reproduce:

```sh
git clone github.com/metanorma/mn-samples-ogc
cd mn-samples-ogc
bundle
cd sources/14-065r2
bundle exec metanorma document.adoc
```

Output:
```
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/mn2pdf-1.38.1/lib/../bin/mn2pdf.jar --xml-file "document.presentation.xml" --xsl-file "/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-ogc-1.5.3/lib/isodoc/ogc/ogc.standard.xsl" --pdf-file "document.pdf" --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20211211-23751-z73h7i.yml"
[mn2pdf] Fatal: mn2pdf Preparing...
Input: XML (document.presentation.xml)
Input: XSL (/Users/me/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/metanorma-ogc-1.5.3/lib/isodoc/ogc/ogc.standard.xsl)
Output: PDF (document.pdf)

[INFO] XSL-FO file preparation...
Transforming to PDF...
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
java.awt.FontFormatException: bad pfa font
	at java.desktop/sun.font.Type1Font.verifyPFA(Type1Font.java:321)
	at java.desktop/sun.font.Type1Font.verify(Type1Font.java:299)
	at java.desktop/sun.font.Type1Font.<init>(Type1Font.java:172)
	at java.desktop/sun.font.SunFontManager.createFont2D(SunFontManager.java:2258)
	at java.desktop/java.awt.Font.<init>(Font.java:615)
	at java.desktop/java.awt.Font.createFont(Font.java:1219)
	at org.metanorma.fop.fontConfig.registerFont(fontConfig.java:785)
	at org.metanorma.fop.fontConfig.lambda$updateFontsForGraphicsEnvironment$28(fontConfig.java:768)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.metanorma.fop.fontConfig.updateFontsForGraphicsEnvironment(fontConfig.java:767)
	at org.metanorma.fop.fontConfig.updateConfig(fontConfig.java:445)
	at org.metanorma.fop.fontConfig.getConfig(fontConfig.java:736)
	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:367)
	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:314)
	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:192)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:174)
Default page-height set to: 11.00in
Default page-width set to: 8.50in
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
Rendered page #1.
The contents of fo:region-after on page ii exceed the available area in the block-progression direction by 17007 millipoints. (See position 14:401)
Rendered page #2.
An fo:block  (See position 109:34684) is wider than the available room in inline-progression-dimension. Adjusting end-indent based on overconstrained geometry rules (XSL 1.1, ch. 5.3.4)
An fo:block  (See position 109:38425) is wider than the available room in inline-progression-dimension. Adjusting end-indent based on overconstrained geometry rules (XSL 1.1, ch. 5.3.4)
The contents of fo:region-after on page iii exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page iv exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page v exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page vi exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page vii exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page viii exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page ix exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page x exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page xi exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page xii exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page xiii exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page xiv exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page xv exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page xvi exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page xvii exceed the available area in the block-progression direction by 17007 millipoints. (See position 109:357)
The contents of fo:region-after on page 1 exceed the available area in the block-progression direction by 17007 millipoints. (See position 209:218)
The contents of fo:region-after on page 2 exceed the available area in the block-progression direction by 17007 millipoints. (See position 215:881)
The contents of fo:region-after on page 3 exceed the available area in the block-progression direction by 17007 millipoints. (See position 240:263)
The contents of fo:region-after on page 4 exceed the available area in the block-progression direction by 17007 millipoints. (See position 246:1157)
The contents of fo:region-after on page 5 exceed the available area in the block-progression direction by 17007 millipoints. (See position 314:226)
The contents of fo:region-after on page 6 exceed the available area in the block-progression direction by 17007 millipoints. (See position 320:1571)
The contents of fo:region-after on page 7 exceed the available area in the block-progression direction by 17007 millipoints. (See position 326:5428)
The contents of fo:region-after on page 8 exceed the available area in the block-progression direction by 17007 millipoints. (See position 332:1617)
The contents of fo:region-after on page 9 exceed the available area in the block-progression direction by 17007 millipoints. (See position 332:1617)
The contents of fo:region-after on page 10 exceed the available area in the block-progression direction by 17007 millipoints. (See position 332:1617)
The contents of fo:region-after on page 11 exceed the available area in the block-progression direction by 17007 millipoints. (See position 383:205)
The contents of fo:region-after on page 12 exceed the available area in the block-progression direction by 17007 millipoints. (See position 389:1157)
The contents of fo:region-after on page 13 exceed the available area in the block-progression direction by 17007 millipoints. (See position 389:1157)
The contents of fo:region-after on page 14 exceed the available area in the block-progression direction by 17007 millipoints. (See position 515:237)
The contents of fo:region-after on page 15 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 16 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 17 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 18 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 19 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 20 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 21 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 22 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 23 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 24 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 25 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 26 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 27 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 28 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 29 exceed the available area in the block-progression direction by 17007 millipoints. (See position 521:1571)
The contents of fo:region-after on page 30 exceed the available area in the block-progression direction by 17007 millipoints. (See position 954:942)
The contents of fo:region-after on page 31 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 32 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 33 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 34 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 35 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 36 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 37 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 38 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 39 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 40 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 41 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 42 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 43 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 44 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 45 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 46 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
Rendered page #3.
The contents of fo:region-after on page 47 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 48 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 49 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 50 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 51 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 52 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 53 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 54 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 55 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 56 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 57 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 58 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 59 exceed the available area in the block-progression direction by 17007 millipoints. (See position 960:1755)
The contents of fo:region-after on page 60 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2230:248)
The contents of fo:region-after on page 61 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2236:2169)
The contents of fo:region-after on page 62 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2236:2169)
The contents of fo:region-after on page 63 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2236:2169)
The contents of fo:region-after on page 64 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2236:2169)
The contents of fo:region-after on page 65 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2337:205)
The contents of fo:region-after on page 66 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 67 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 68 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 69 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 70 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 71 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 72 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 73 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 74 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 75 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 76 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 77 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 78 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 79 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 80 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 81 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 82 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 83 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 84 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 85 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 86 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 87 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 88 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 89 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 90 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 91 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 92 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 93 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 94 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 95 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 96 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 97 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 98 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 99 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 100 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 101 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 102 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 103 exceed the available area in the block-progression direction by 17007 millipoints. (See position 2343:1755)
The contents of fo:region-after on page 104 exceed the available area in the block-progression direction by 17007 millipoints. (See position 3844:327)
The contents of fo:region-after on page 105 exceed the available area in the block-progression direction by 17007 millipoints. (See position 3850:2353)
The contents of fo:region-after on page 106 exceed the available area in the block-progression direction by 17007 millipoints. (See position 3850:2353)
The contents of fo:region-after on page 107 exceed the available area in the block-progression direction by 17007 millipoints. (See position 3850:2353)
The contents of fo:region-after on page 108 exceed the available area in the block-progression direction by 17007 millipoints. (See position 3850:2353)
The contents of fo:region-after on page 109 exceed the available area in the block-progression direction by 17007 millipoints. (See position 3850:2353)
The contents of fo:region-after on page 110 exceed the available area in the block-progression direction by 17007 millipoints. (See position 3850:2353)
The contents of fo:region-after on page 111 exceed the available area in the block-progression direction by 17007 millipoints. (See position 3850:2353)
The contents of fo:region-after on page 112 exceed the available area in the block-progression direction by 17007 millipoints. (See position 3850:2353)
The contents of fo:region-after on page 113 exceed the available area in the block-progression direction by 17007 millipoints. (See position 3850:2353)
The contents of fo:region-after on page 114 exceed the available area in the block-progression direction by 17007 millipoints. (See position 3850:2353)
The contents of fo:region-after on page 115 exceed the available area in the block-progression direction by 17007 millipoints. (See position 4201:248)
javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: "fo:list-item" is not a valid child of "fo:block"! (See position 4238:21)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:428)
	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:314)
	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:192)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:174)
Caused by: org.apache.fop.fo.ValidationException: "fo:list-item" is not a valid child of "fo:block"! (See position 4238:21)
	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
	at com.sun.proxy.$Proxy12.invalidChild(Unknown Source)
	at org.apache.fop.fo.FONode.invalidChildError(FONode.java:581)
	at org.apache.fop.fo.FONode.invalidChildError(FONode.java:557)
	at org.apache.fop.fo.flow.Block.validateChildNode(Block.java:294)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:277)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
	at org.apache.xalan.transformer.TransformerIdentityImpl.startElement(TransformerIdentityImpl.java:1073)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2725)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:541)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	... 4 more
---------
org.apache.fop.fo.ValidationException: "fo:list-item" is not a valid child of "fo:block"! (See position 4238:21)
	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
	at com.sun.proxy.$Proxy12.invalidChild(Unknown Source)
	at org.apache.fop.fo.FONode.invalidChildError(FONode.java:581)
	at org.apache.fop.fo.FONode.invalidChildError(FONode.java:557)
	at org.apache.fop.fo.flow.Block.validateChildNode(Block.java:294)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:277)
	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
	at org.apache.xalan.transformer.TransformerIdentityImpl.startElement(TransformerIdentityImpl.java:1073)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2725)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:541)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:428)
	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:314)
	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:192)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:174)
XSL-FO file for debugging saved into: /Users/me/src/mn/mn-samples-ogc/sources/14-065r2/document.pdf.fo.debug.xml
```

The resulting PDF is 0 bytes, and this is the cause of https://github.com/metanorma/packed-mn/issues/135 and https://github.com/metanorma/packed-mn/pull/136 failing.

We should run mn-samples-ogc for metanorma-ogc success testing.

**Comment by Intelligent2013** [comment]
@ronaldtse in the metanorma presentation xml there isn't parent element `ol` for `li`:

Presentation xml:
```xml
<tr>
	<td colspan="2">
		<p id="_05fc4e93-84f7-fba3-f0e4-054a9b67fb80">
			<em>The Basic WPS server shall support one or more of the following bindings for each operation:</em>
		</p>
	</td>
</tr>
<tr>
	<td colspan="2">
		<li>
			<p id="_57a7d3f0-1fbf-7378-938c-3fb4a78fdca7">
				<link target="http://www.opengis.net/spec/WPS/2.0/req/service/binding/post-xml"/>
			</p>
		</li>
		<li>
			<p id="_dbf04112-04f5-4efb-fa22-8d94f58e1e2a">
				<link target="http://www.opengis.net/spec/WPS/2.0/req/service/binding/get-kvp"/>
			</p>
		</li>
	</td>
</tr>
```

Semantic xml:
```xml
<description>
	<p id="_05fc4e93-84f7-fba3-f0e4-054a9b67fb80">
		<em>The Basic WPS server shall support one or more of the following bindings for each operation:</em>
	</p>
</description>
<ol id="_ce1c69ff-b282-b741-5e86-611bc40e3770" type="arabic">
	<li>
		<p id="_57a7d3f0-1fbf-7378-938c-3fb4a78fdca7">
			<link target="http://www.opengis.net/spec/WPS/2.0/req/service/binding/post-xml"/>
		</p>
	</li>
	<li>
		<p id="_dbf04112-04f5-4efb-fa22-8d94f58e1e2a">
			<link target="http://www.opengis.net/spec/WPS/2.0/req/service/binding/get-kvp"/>
		</p>
	</li>
</ol>
```

**Comment by ronaldtse** [comment]
Bringing in @opoudjis

**Comment by opoudjis** [comment]
I've introduced a fix, but this involves a bare `<ol>` in the requirement, and that points to faulty parsing: the `<ol>` should have been read into the `<description>`.

**Comment by opoudjis** [comment]
Issue is that these are bare links, which have no textual content; Metanorma was assuming that they would therefore be removed from the description, as empty of textual content.

**Comment by opoudjis** [comment]
The fixes to metanorma-standoc and metanorma-ogc should have taken care of this.

**Comment by opoudjis** [comment]
@ronaldtse Please confirm this is fixed.

**Comment by opoudjis** [comment]
... I've confirmed it with latest release.

**Comment by ronaldtse** [comment]
Also confirmed. Thanks @opoudjis @Intelligent2013 !

<img width="680" alt="Screenshot 2021-12-14 at 12 36 02 PM" src="https://user-images.githubusercontent.com/11865/145933769-bebbd94f-7753-47a2-aab8-9398e6381ae3.png">
