### ISSUE TITLE
Large single line Source Code example files in PDF generation

### ISSUE THREAD

**Issue by gbuehler** [metanorma/metanorma-ogc#385]
When we try to add the following source code block to the asciidoc, the Metanorma pipeline fails on PDF generation.  It is a single line of 6035 characters. 

```
.Base64 encoded data URI
----
data:application/xacml+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48IS0tVGhpcyBmaWxlIHdhcyBnZW5lcmF0ZWQgYnkgdGhlIEFMRkEgUGx1Z2luIGZvciBFY2xpcHNlIGZyb20gQXhpb21hdGljcyBBQiAoaHR0cDovL3d3dy5heGlvbWF0aWNzLmNvbSkuLS0+PCEtLUFueSBtb2RpZmljYXRpb24gdG8gdGhpcyBmaWxlIHdpbGwgYmUgbG9zdCB1cG9uIHJlY29tcGlsYXRpb24gb2YgdGhlIHNvdXJjZSBBTEZBIGZpbGUtLT48eGFjbWwzOlBvbGljeSB4bWxuczp4YWNtbDM9InVybjpvYXNpczpuYW1lczp0Yzp4YWNtbDozLjA6Y29yZTpzY2hlbWE6d2QtMTciIFBvbGljeUlkPSJodHRwOi8vYXhpb21hdGljcy5jb20vYWxmYS9pZGVudGlmaWVyL0tNUy5CdXNpbmVzc0xvZ2ljIiBSdWxlQ29tYmluaW5nQWxnSWQ9InVybjpvYXNpczpuYW1lczp0Yzp4YWNtbDozLjA6cnVsZS1jb21iaW5pbmctYWxnb3JpdGhtOnBlcm1pdC1vdmVycmlkZXMiIFZlcnNpb249IjEuMCI+PHhhY21sMzpEZXNjcmlwdGlvbi8+PHhhY21sMzpQb2xpY3lEZWZhdWx0cz48eGFjbWwzOlhQYXRoVmVyc2lvbj5odHRwOi8vd3d3LnczLm9yZy9UUi8xOTk5L1JFQy14cGF0aC0xOTk5MTExNjwveGFjbWwzOlhQYXRoVmVyc2lvbj48L3hhY21sMzpQb2xpY3lEZWZhdWx0cz48eGFjbWwzOlRhcmdldC8+PHhhY21sMzpSdWxlIEVmZmVjdD0iUGVybWl0IiBSdWxlSWQ9IktNUy5CdXNpbmVzc0xvZ2ljI3J1bGVfMSI+PHhhY21sMzpEZXNjcmlwdGlvbi8+PHhhY21sMzpUYXJnZXQ+PHhhY21sMzpBbnlPZj48eGFjbWwzOkFsbE9mPjx4YWNtbDM6TWF0Y2ggTWF0Y2hJZD0idXJuOm9hc2lzOm5hbWVzOnRjOnhhY21sOjEuMDpmdW5jdGlvbjpzdHJpbmctZXF1YWwiPjx4YWNtbDM6QXR0cmlidXRlVmFsdWUgRGF0YVR5cGU9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hI3N0cmluZyI+cmVhZDwveGFjbWwzOkF0dHJpYnV0ZVZhbHVlPjx4YWNtbDM6QXR0cmlidXRlRGVzaWduYXRvciBBdHRyaWJ1dGVJZD0idXJuOm9hc2lzOm5hbWVzOnRjOnhhY21sOjEuMDphY3Rpb246YWN0aW9uLWlkIiBDYXRlZ29yeT0idXJuOm9hc2lzOm5hbWVzOnRjOnhhY21sOjMuMDphdHRyaWJ1dGUtY2F0ZWdvcnk6YWN0aW9uIiBEYXRhVHlwZT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEjc3RyaW5nIiBNdXN0QmVQcmVzZW50PSJmYWxzZSIvPjwveGFjbWwzOk1hdGNoPjwveGFjbWwzOkFsbE9mPjwveGFjbWwzOkFueU9mPjwveGFjbWwzOlRhcmdldD48eGFjbWwzOkNvbmRpdGlvbj48eGFjbWwzOkFwcGx5IEZ1bmN0aW9uSWQ9InVybjpvYXNpczpuYW1lczp0Yzp4YWNtbDoxLjA6ZnVuY3Rpb246YW5kIj48eGFjbWwzOkFwcGx5IEZ1bmN0aW9uSWQ9InVybjpvYXNpczpuYW1lczp0Yzp4YWNtbDozLjA6ZnVuY3Rpb246YW55LW9mLWFueSI+PHhhY21sMzpGdW5jdGlvbiBGdW5jdGlvbklkPSJ1cm46b2FzaXM6bmFtZXM6dGM6eGFjbWw6MS4wOmZ1bmN0aW9uOmJvb2xlYW4tZXF1YWwiLz48eGFjbWwzOkF0dHJpYnV0ZURlc2lnbmF0b3IgQXR0cmlidXRlSWQ9InVybjpzZDprZXk6YWN0aXZlIiBDYXRlZ29yeT0idXJuOm9hc2lzOm5hbWVzOnRjOnhhY21sOjMuMDphdHRyaWJ1dGUtY2F0ZWdvcnk6ZW52aXJvbm1lbnQiIERhdGFUeXBlPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSNib29sZWFuIiBNdXN0QmVQcmVzZW50PSJmYWxzZSIvPjx4YWNtbDM6QXR0cmlidXRlVmFsdWUgRGF0YVR5cGU9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hI2Jvb2xlYW4iPnRydWU8L3hhY21sMzpBdHRyaWJ1dGVWYWx1ZT48L3hhY21sMzpBcHBseT48eGFjbWwzOkFwcGx5IEZ1bmN0aW9uSWQ9InVybjpvYXNpczpuYW1lczp0Yzp4YWNtbDoxLjA6ZnVuY3Rpb246YW5kIj48eGFjbWwzOkFwcGx5IEZ1bmN0aW9uSWQ9InVybjpvYXNpczpuYW1lczp0Yzp4YWNtbDoxLjA6ZnVuY3Rpb246c3RyaW5nLWF0LWxlYXN0LW9uZS1tZW1iZXItb2YiPjx4YWNtbDM6QXR0cmlidXRlRGVzaWduYXRvciBBdHRyaWJ1dGVJZD0idXJuOm9hc2lzOm5hbWVzOnRjOnhhY21sOjEuMDpzdWJqZWN0OnN1YmplY3QtaWQiIENhdGVnb3J5PSJ1cm46b2FzaXM6bmFtZXM6dGM6eGFjbWw6MS4wOnN1YmplY3QtY2F0ZWdvcnk6YWNjZXNzLXN1YmplY3QiIERhdGFUeXBlPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSNzdHJpbmciIE11c3RCZVByZXNlbnQ9ImZhbHNlIi8+PHhhY21sMzpBdHRyaWJ1dGVEZXNpZ25hdG9yIEF0dHJpYnV0ZUlkPSJ1cm46c2Q6a2V5OnN1YmplY3RzIiBDYXRlZ29yeT0idXJuOm9hc2lzOm5hbWVzOnRjOnhhY21sOjMuMDphdHRyaWJ1dGUtY2F0ZWdvcnk6cmVzb3VyY2UiIERhdGFUeXBlPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSNzdHJpbmciIE11c3RCZVByZXNlbnQ9ImZhbHNlIi8+PC94YWNtbDM6QXBwbHk+PHhhY21sMzpBcHBseSBGdW5jdGlvbklkPSJ1cm46b2FzaXM6bmFtZXM6dGM6eGFjbWw6MS4wOmZ1bmN0aW9uOmFuZCI+PHhhY21sMzpBcHBseSBGdW5jdGlvbklkPSJ1cm46b2FzaXM6bmFtZXM6dGM6eGFjbWw6MS4wOmZ1bmN0aW9uOnN0cmluZy1hdC1sZWFzdC1vbmUtbWVtYmVyLW9mIj48eGFjbWwzOkF0dHJpYnV0ZURlc2lnbmF0b3IgQXR0cmlidXRlSWQ9InVybjpzZDpjbGllbnRfaWQiIENhdGVnb3J5PSJ1cm46b2FzaXM6bmFtZXM6dGM6eGFjbWw6My4wOmF0dHJpYnV0ZS1jYXRlZ29yeTpyZXNvdXJjZSIgRGF0YVR5cGU9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hI3N0cmluZyIgTXVzdEJlUHJlc2VudD0iZmFsc2UiLz48eGFjbWwzOkF0dHJpYnV0ZURlc2lnbmF0b3IgQXR0cmlidXRlSWQ9InVybjpzZDprZXk6YXVkaWVuY2VzIiBDYXRlZ29yeT0idXJuOm9hc2lzOm5hbWVzOnRjOnhhY21sOjMuMDphdHRyaWJ1dGUtY2F0ZWdvcnk6cmVzb3VyY2UiIERhdGFUeXBlPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYSNzdHJpbmciIE11c3RCZVByZXNlbnQ9ImZhbHNlIi8+PC94YWNtbDM6QXBwbHk+PHhhY21sMzpBcHBseSBGdW5jdGlvbklkPSJ1cm46b2FzaXM6bmFtZXM6dGM6eGFjbWw6MS4wOmZ1bmN0aW9uOmFuZCI+PHhhY21sMzpBcHBseSBGdW5jdGlvbklkPSJ1cm46b2FzaXM6bmFtZXM6dGM6eGFjbWw6My4wOmZ1bmN0aW9uOmFueS1vZi1hbnkiPjx4YWNtbDM6RnVuY3Rpb24gRnVuY3Rpb25JZD0idXJuOm9hc2lzOm5hbWVzOnRjOnhhY21sOjEuMDpmdW5jdGlvbjpkYXRlVGltZS1ncmVhdGVyLXRoYW4tb3ItZXF1YWwiLz48eGFjbWwzOkF0dHJpYnV0ZURlc2lnbmF0b3IgQXR0cmlidXRlSWQ9InVybjpvYXNpczpuYW1lczp0Yzp4YWNtbDoxLjA6ZW52aXJvbm1lbnQ6Y3VycmVudC1kYXRlVGltZSIgQ2F0ZWdvcnk9InVybjpvYXNpczpuYW1lczp0Yzp4YWNtbDozLjA6YXR0cmlidXRlLWNhdGVnb3J5OmVudmlyb25tZW50IiBEYXRhVHlwZT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEjZGF0ZVRpbWUiIE11c3RCZVByZXNlbnQ9ImZhbHNlIi8+PHhhY21sMzpBdHRyaWJ1dGVEZXNpZ25hdG9yIEF0dHJpYnV0ZUlkPSJ1cm46c2Q6a2V5Om5vdC1iZWZvcmUiIENhdGVnb3J5PSJ1cm46b2FzaXM6bmFtZXM6dGM6eGFjbWw6My4wOmF0dHJpYnV0ZS1jYXRlZ29yeTplbnZpcm9ubWVudCIgRGF0YVR5cGU9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hI2RhdGVUaW1lIiBNdXN0QmVQcmVzZW50PSJmYWxzZSIvPjwveGFjbWwzOkFwcGx5Pjx4YWNtbDM6QXBwbHkgRnVuY3Rpb25JZD0idXJuOm9hc2lzOm5hbWVzOnRjOnhhY21sOjMuMDpmdW5jdGlvbjphbnktb2YtYW55Ij48eGFjbWwzOkZ1bmN0aW9uIEZ1bmN0aW9uSWQ9InVybjpvYXNpczpuYW1lczp0Yzp4YWNtbDoxLjA6ZnVuY3Rpb246ZGF0ZVRpbWUtbGVzcy10aGFuLW9yLWVxdWFsIi8+PHhhY21sMzpBdHRyaWJ1dGVEZXNpZ25hdG9yIEF0dHJpYnV0ZUlkPSJ1cm46b2FzaXM6bmFtZXM6dGM6eGFjbWw6MS4wOmVudmlyb25tZW50OmN1cnJlbnQtZGF0ZVRpbWUiIENhdGVnb3J5PSJ1cm46b2FzaXM6bmFtZXM6dGM6eGFjbWw6My4wOmF0dHJpYnV0ZS1jYXRlZ29yeTplbnZpcm9ubWVudCIgRGF0YVR5cGU9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hI2RhdGVUaW1lIiBNdXN0QmVQcmVzZW50PSJmYWxzZSIvPjx4YWNtbDM6QXR0cmlidXRlRGVzaWduYXRvciBBdHRyaWJ1dGVJZD0idXJuOnNkOmtleTpub3QtYWZ0ZXIiIENhdGVnb3J5PSJ1cm46b2FzaXM6bmFtZXM6dGM6eGFjbWw6My4wOmF0dHJpYnV0ZS1jYXRlZ29yeTplbnZpcm9ubWVudCIgRGF0YVR5cGU9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hI2RhdGVUaW1lIiBNdXN0QmVQcmVzZW50PSJmYWxzZSIvPjwveGFjbWwzOkFwcGx5PjwveGFjbWwzOkFwcGx5PjwveGFjbWwzOkFwcGx5PjwveGFjbWwzOkFwcGx5PjwveGFjbWwzOkFwcGx5PjwveGFjbWwzOkNvbmRpdGlvbj48L3hhY21sMzpSdWxlPjwveGFjbWwzOlBvbGljeT4=
----
```

 If I remove the pdf from generation, I can get the pipeline to process the xml, doc, and HTML.  However the HTML is a single line:

![Screen Shot 2022-06-03 at 9 20 46 AM](https://user-images.githubusercontent.com/221625/171918524-d5cebcf2-c904-46cb-9b62-ae824853359a.png)

I have run the asciidoc with both Asciidoctor and Asciidoctor-PDF and they both look good (screenshots truncated for convenience):

<img width="787" alt="Screen Shot 2022-06-03 at 1 48 13 PM" src="https://user-images.githubusercontent.com/221625/171918801-b2165874-4dc1-49c2-b45f-4a192031444d.png">

<img width="1040" alt="Screen Shot 2022-06-03 at 1 47 52 PM" src="https://user-images.githubusercontent.com/221625/171918804-35b565fe-7cca-4651-a2e1-2cf5e1737f21.png">

We tried to wrapping the text at 87 characters per line. That did not work, neither 80 or 70 worked either.

So far the only thing we can do is truncate the example, which is not ideal as it takes away the option for the reader to test the example:

```
.Base64 encoded data URI (truncated)
----
data:application/xacml+xml;base64,
PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48IS0tVGhpcyBmaWxlIH
dhcyBnZW5lcmF0ZWQgYnkgdGhlIEFMRkEgUGx1Z2luIGZvciBFY2xpcHNlIGZyb20gQXhp
b21hdGljcyBBQiAoaHR0cDovL3d3dy5heGlvbWF0aWNzLmNvbSkuLS0+PCEtLUFueSBtb2
...
----
```

**Comment by Intelligent2013** [comment]
The error
```
[INFO] Generation of XSL-FO with information about the table's widths ...
Exception in thread "main" java.lang.StackOverflowError
        at java.lang.StringBuffer.append(Unknown Source)
        at java.io.StringWriter.write(Unknown Source)
        at org.apache.xml.serializer.ToStream.characters(ToStream.java:1623)
        at org.apache.xml.utils.FastStringBuffer.sendSAXcharacters(FastStringBuffer.java:985)
        at org.apache.xpath.objects.XStringForFSB.dispatchCharactersEvents(XStringForFSB.java:184)
```
occurs due the long source code's text in the xsl template `add_spaces_to_sourcecode`. This template add zero-width spaces into the long string. I'll investigate how to fix it.

**Comment by Intelligent2013** [comment]
Issue fixed:
![image](https://user-images.githubusercontent.com/5559926/171938838-02dd579b-0446-4b0f-a35f-a7ff3ecffb11.png)
(test document rendering)

Updated xslt should be available here: https://github.com/metanorma/metanorma-ogc/tree/main/lib/isodoc/ogc after in ~30min.

**Comment by ronaldtse** [comment]
Thanks @gbuehler for reporting and @Intelligent2013 for fixing. I believe the next release will be on Monday 2022-06-06, so let's try the released version on Monday.

**Comment by ronaldtse** [comment]
@gbuehler can we confirm that this issue is fixed? Thanks.

**Comment by ronaldtse** [comment]
Closing since it has been fixed. Thanks!
