### ISSUE TITLE
The process hangs after relaton error

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-ogc#389]
I'm trying to generate presentation xml for https://github.com/metanorma/ogc-modspec.
```
bundle exec metanorma -t ogc -x presentation document.adoc`
```
Log:
```
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
[relaton-iso] ("ISO/IEC 10000-1") fetching...
[relaton-iso] ("ISO/IEC Directives") fetching...
[relaton-w3c] ("W3C XML Schema Part 1") fetching...
[relaton-omg] no document found for "OMG Unified Modeling Language (OMG UML)" reference.
[relaton-omg] no document found for "OMG Unified Modeling Language (OMG UML)" reference.
[relaton-iso] ("ISO 19105") fetching...
[relaton-w3c] ("W3C XML Schema Part 2") fetching...
#<Thread:0x0000000018f6cc88 C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-1.11.3/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-1.11.3/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
        5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-1.11.3/lib/relaton/db.rb:110:in `block in fetch_async'
        4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-1.11.3/lib/relaton/db.rb:74:in `fetch'
        3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-1.11.3/lib/relaton/db.rb:384:in `check_bibliocache'
        2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-1.11.3/lib/relaton/db_cache.rb:67:in `[]'
        1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-1.11.3/lib/relaton/db_cache.rb:164:in `get'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-1.11.3/lib/relaton/db_cache.rb:164:in `read': Permission denied @ io_fillbuf - fd:6 D:/Metanorma/repositories/ogc-modspec/sources/relaton/cache/omg/omg_unified_modeling_language_omg_uml.notfound (Errno::EACCES)
[relaton-w3c] ("W3C XML Schema Part 1") not found.
[relaton-w3c] ("W3C XML Schema Part 2") not found.
[relaton-iso] ("ISO/IEC 10000-1") found ISO/IEC TR 10000-1:1998
[relaton-iso] ("ISO/IEC 19501") fetching...
[relaton-iso] ("ISO 19105") found ISO 19105:2000
[relaton-iso] ("ISO/IEC 19757-3") fetching...
[relaton-iso] ("ISO/IEC Directives") found ISO/IEC/IEEE 32430:2021
[relaton-iso] ("ISO/IEC Directives/Part 2") fetching...
[relaton-iso] WARNING: no match found online for ISO/IEC Directives/Part 2. The code must be exactly like it is on the standards website.
[relaton-iso] If you wanted to cite all document parts for the reference, use "ISO/IEC Directives/Part 2 (all parts)".
If the document is not a standard, use its document type abbreviation (TS, TR, PAS, Guide).
[relaton-iso] ("ISO/IEC 19501") found ISO/IEC 19501:2005
[relaton-iso] ("ISO/IEC 19757-3") found ISO/IEC 19757-3:2006
```
And nothing... I've waited 10min and there isn't any activity after the last line `[relaton-iso] ("ISO/IEC 19501") found ISO/IEC 19501:2005`

**Comment by Intelligent2013** [comment]
The issue occurs due the line
```
* [[[omg2007-infrastructure,Object Management Group (OMG)]]], Object Management Group (OMG), February 2007, Unified Modeling Language: Infrastructure , version 2.1.1 , formal/07-02-06, available from OMG.org at http://www.omg.org/cgi-bin/doc?formal/07-02-06
```
in `ad-bibliography.adoc`.

**Comment by opoudjis** [comment]
Cannot replicate, but will need to try to catch crashes in async fetching, this has happened before...

**Comment by Intelligent2013** [comment]
Hmm, done successfully too. After 3 attempts.

**Comment by ronaldtse** [comment]
The gang may be due to relaton-ogc , even though this has been fixed before. It might be a regression. @andrew2net can you help check?

**Comment by Intelligent2013** [comment]
> Maybe the file was created by another Windows user.

@andrew2net no, the same user, the same cmd console. 1st and 2nd attempts hang, but 3rd ended successfully.

**Comment by opoudjis** [comment]
By the way, I see that errors are being caught in the main async loop:

````
          wp = WorkersPool.new(threads) do |args|
            args[3].call fetch(*args[0..2])
          rescue RelatonBib::RequestError => e
            args[3].call e
          end
          @queues[stdclass] = { queue: Queue.new, workers_pool: wp }
          Thread.new { process_queue @queues[stdclass] }

````

but crashes like this are resulting in the thread never being closed:

````
      @threads = Array.new workers do
        Thread.new do
          while item = @queue.pop; yield(item) end
        end
      end
````

Async is not my strength. Is this because, if the crash happens,  and the rescue is invoked,

````
          @queues[stdclass] = { queue: Queue.new, workers_pool: wp }
          Thread.new { process_queue @queues[stdclass] }
````

needs to be suppressed?

**Comment by andrew2net** [comment]
> By the way, I see that errors are being caught in the main async loop:

It catches `RelatonBib::RequestError` only now, but we have `Errno::EACCES` in this case. I'll make the script catch any errors, log them and return nil (which means the document isn't found).
