### ISSUE TITLE
Compilation failure in Metanorma-OGC with requirements

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#413]
```
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.2.1.1/lib/metanorma/standoc/reqt.rb:23:in `requirement': wrong number of arguments (given 2, expected 3) (ArgumentError)
	from ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-ogc-2.2.1/lib/metanorma/ogc/converter.rb:143:in `example'
	from ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-standoc-2.2.1.1/lib/metanorma/standoc/utils.rb:13:in `convert'
	from ruby/3.1.2/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.17/lib/asciidoctor/abstract_block.rb:75:in `convert'
```

This is from geopose.

That said I have not labeled the `:requirements-model: ogc` yet. But this ought to be default in OGC.

**Comment by ronaldtse** [comment]
Same failure.

**Comment by ronaldtse** [comment]
Failure occurs here: https://github.com/metanorma/ogc-GeoPose/pull/2

**Comment by ronaldtse** [comment]
While the Windows platform is still not fixed, the rest are fixed. Closing.
