### ISSUE TITLE
Support source code "Key" via AsciiDoc target item annotation (originally mn2pdf crashing on rendering)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#517]
```
[mn2pdf] Fatal error!
[mn2pdf] STDOUT:
[mn2pdf] mn2pdf 
[mn2pdf] 
[mn2pdf] 
[mn2pdf] [INFO] Rendering into intermediate format ...
[mn2pdf] STDERR:
[mn2pdf] Preparing...
[mn2pdf] Input: XML (~/ogc-muddi-mds/_site/documents/mds-guide/document.presentation.xml)
[mn2pdf] Input: XSL (lib/ruby/gems/3.1.0/gems/metanorma-ogc-2.3.6/lib/isodoc/ogc/ogc.best-practice.xsl)
[mn2pdf] Input: XSL parameters ({baseassetpath=~/ogc-muddi-mds/sources/mds-guide})
[mn2pdf] Output: PDF (~/ogc-muddi-mds/_site/documents/mds-guide/document.pdf)
[mn2pdf] 
[mn2pdf] [INFO] Generation of XSL-FO with information about the table's widths ...
[mn2pdf] [INFO] Generation of Intermediate Format with information about the table's widths ...
[mn2pdf] java.awt.FontFormatException: bad pfa font
[mn2pdf] 	at java.desktop/sun.font.Type1Font.verifyPFA(Type1Font.java:324)
[mn2pdf] 	at java.desktop/sun.font.Type1Font.verify(Type1Font.java:302)
[mn2pdf] 	at java.desktop/sun.font.Type1Font.<init>(Type1Font.java:172)
[mn2pdf] 	at java.desktop/sun.font.SunFontManager.createFont2D(SunFontManager.java:2223)
[mn2pdf] 	at java.desktop/java.awt.Font.<init>(Font.java:644)
[mn2pdf] 	at java.desktop/java.awt.Font.createFont(Font.java:1250)
[mn2pdf] 	at org.metanorma.fop.fontConfig.registerFont(fontConfig.java:837)
[mn2pdf] 	at org.metanorma.fop.fontConfig.lambda$updateFontsForGraphicsEnvironment$33(fontConfig.java:807)
[mn2pdf] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[mn2pdf] 	at org.metanorma.fop.fontConfig.updateFontsForGraphicsEnvironment(fontConfig.java:806)
[mn2pdf] 	at org.metanorma.fop.fontConfig.updateConfig(fontConfig.java:463)
[mn2pdf] 	at org.metanorma.fop.fontConfig.getConfig(fontConfig.java:774)
[mn2pdf] 	at org.metanorma.fop.PDFGenerator.setTablesWidths(PDFGenerator.java:1147)
[mn2pdf] 	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:390)
[mn2pdf] 	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:301)
[mn2pdf] 	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:338)
[mn2pdf] [INFO] Intermediate format. Rendered page #1.
[mn2pdf] [INFO] Intermediate format. Rendered page #2.
[mn2pdf] [FATAL] Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 578:537)
[mn2pdf] Can't obtain tables widths information: {0}
[mn2pdf] [INFO] XSL-FO file preparation...
[mn2pdf] Transforming to Intermediate Format...
[mn2pdf] java.awt.FontFormatException: bad pfa font
[mn2pdf] 	at java.desktop/sun.font.Type1Font.verifyPFA(Type1Font.java:324)
[mn2pdf] 	at java.desktop/sun.font.Type1Font.verify(Type1Font.java:302)
[mn2pdf] 	at java.desktop/sun.font.Type1Font.<init>(Type1Font.java:172)
[mn2pdf] 	at java.desktop/sun.font.SunFontManager.createFont2D(SunFontManager.java:2223)
[mn2pdf] 	at java.desktop/java.awt.Font.<init>(Font.java:644)
[mn2pdf] 	at java.desktop/java.awt.Font.createFont(Font.java:1250)
[mn2pdf] 	at org.metanorma.fop.fontConfig.registerFont(fontConfig.java:837)
[mn2pdf] 	at org.metanorma.fop.fontConfig.lambda$updateFontsForGraphicsEnvironment$33(fontConfig.java:807)
[mn2pdf] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[mn2pdf] 	at org.metanorma.fop.fontConfig.updateFontsForGraphicsEnvironment(fontConfig.java:806)
[mn2pdf] 	at org.metanorma.fop.fontConfig.updateConfig(fontConfig.java:463)
[mn2pdf] 	at org.metanorma.fop.fontConfig.getConfig(fontConfig.java:774)
[mn2pdf] 	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:460)
[mn2pdf] 	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:422)
[mn2pdf] 	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:301)
[mn2pdf] 	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:338)
[mn2pdf] Rendered page #1.
[mn2pdf] Rendered page #2.
[mn2pdf] An fo:block  (See position 37:26367) is wider than the available room in inline-progression-dimension. Adjusting end-indent based on overconstrained geometry rules (XSL 1.1, ch. 5.3.4)
[mn2pdf] The contents of fo:inline line 1 exceed the available area in the inline-progression direction by 462 millipoints. (See position 216:320)
[mn2pdf] The contents of fo:inline line 1 exceed the available area in the inline-progression direction by 462 millipoints. (See position 224:322)
[mn2pdf] The contents of fo:inline line 1 exceed the available area in the inline-progression direction by 462 millipoints. (See position 230:321)
[mn2pdf] The contents of fo:inline line 1 exceed the available area in the inline-progression direction by 462 millipoints. (See position 237:323)
[mn2pdf] Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1197:537)
[mn2pdf] org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1197:537)
[mn2pdf] javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1197:537)
[mn2pdf] 	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
[mn2pdf] 	at org.metanorma.fop.PDFGenerator.generateFOPIntermediateFormat(PDFGenerator.java:714)
[mn2pdf] 	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:460)
[mn2pdf] 	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:422)
[mn2pdf] 	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:301)
[mn2pdf] 	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:338)
[mn2pdf] Caused by: org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1197:537)
[mn2pdf] 	at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)
[mn2pdf] 	at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:58)
[mn2pdf] 	at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:173)
[mn2pdf] 	at jdk.proxy2/jdk.proxy2.$Proxy10.missingLinkDestination(Unknown Source)
[mn2pdf] 	at org.apache.fop.fo.flow.BasicLink.bind(BasicLink.java:95)
[mn2pdf] 	at org.apache.fop.fo.FObj.processNode(FObj.java:131)
[mn2pdf] 	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.startElement(FOTreeBuilder.java:293)
[mn2pdf] 	at org.apache.fop.fo.FOTreeBuilder.startElement(FOTreeBuilder.java:179)
[mn2pdf] 	at org.apache.xalan.transformer.TransformerIdentityImpl.startElement(TransformerIdentityImpl.java:1073)
[mn2pdf] 	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
[mn2pdf] 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
[mn2pdf] 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2726)
[mn2pdf] 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
[mn2pdf] 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
[mn2pdf] 	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
[mn2pdf] 	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
[mn2pdf] 	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
[mn2pdf] 	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
[mn2pdf] 	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
[mn2pdf] 	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
[mn2pdf] 	... 5 more
[mn2pdf] ---------
```

**Comment by Intelligent2013** [comment]
PDF locally generated successfully, but there is an error on the annotation processing:
```
Can't flat IF.
java.lang.NumberFormatException: For input string: "50%"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseFloat(Unknown Source)
        at java.lang.Float.parseFloat(Unknown Source)
        at org.metanorma.fop.ifhandler.FOPIFFlatHandler.startElement(FOPIFFlatHandler.java:94)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
        at org.metanorma.fop.PDFGenerator.flatIFforXFDF(PDFGenerator.java:827)
        at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:621)
        at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:442)
        at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:305)
        at org.metanorma.fop.mn2pdf.main(mn2pdf.java:345)
PDFGenerator.applyXSLTExtended[xfdf_simple.xsl] processing time: 183 milliseconds
Can't add annotation.
java.lang.ArrayIndexOutOfBoundsException: 1
        at org.metanorma.fop.annotations.Annotation.process(Annotation.java:145)
        at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:630)
        at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:442)
        at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:305)
        at org.metanorma.fop.mn2pdf.main(mn2pdf.java:345)
PDFGenerator.runFOP[] processing time: 10611 milliseconds
Success!
```

I'll investigate it.

**Comment by Intelligent2013** [comment]
@ronaldtse I can't repeat the issue:
```
[mn2pdf] Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1197:537)
[mn2pdf] org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1197:537)
[mn2pdf] javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1197:537)
[mn2pdf] 	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
```

Could you attach the `document.presentation.pdf.fo.xml` file?

**Comment by Intelligent2013** [comment]
Adoc:
```adoc
.Terms and definitions in Metanorma AsciiDoc
[source,adoc]
----
== Terms and definitions <1>

==== conceptual model <2>
alt:[CM] <3>

model that defines concepts of a universe of discourse <4>

[.source]
<<ISO_19101-1,clause=4.1.5>> <5>

==== logical model

model that implements a {{conceptual model}} at a logical level <6>
----

// <1> Mandatory clause title
// <2> Term for concept
// <3> Alternate term for concept
// <4> Definition of concept
// <5> Source of concept
// <6> Concept mention of a defined term in the same document

```

```xml
<sourcecode id="_e4d6f30c-1d1a-fbf7-0df9-e263ac37f2bb" lang="adoc"><name>Figure 30 — Terms and definitions in Metanorma AsciiDoc</name>== Terms and definitions <span class="c"><callout>1</callout></span> 

==== conceptual model <span class="c"><callout>2</callout></span> 
alt:[CM] <span class="c"><callout>3</callout></span> 

model that defines concepts of a universe of discourse <span class="c"><callout>4</callout></span> 

[.source]
&#x3c;&#x3c;ISO_19101-1,clause=4.1.5&#x3e;&#x3e; <span class="c"><callout>5</callout></span> 

==== logical model

model that implements a {{conceptual model}} at a logical level <span class="c"><callout>6</callout></span> </sourcecode>
```

The issue in empty `<fo:basic-link fox:alt-text="" internal-destination="">&lt;1&gt;</fo:basic-link>` in XSL-FO:
```xml
<fo:block-container margin-left="0mm" id="_e4d6f30c-1d1a-fbf7-0df9-e263ac37f2bb"><fo:block-container margin-left="0mm"><fo:block white-space="pre" wrap-option="wrap" role="Code" font-family="Fira Code, Noto Sans Mono, Noto Sans Mono CJK HK, Noto Sans Mono CJK JP, Noto Sans Mono CJK KR, Noto Sans Mono CJK SC, Noto Sans Mono CJK TC" margin-bottom="6pt" line-height="113%" font-size="9.5pt" color="rgb(68, 68, 68)">=​​=​​ ​Terms ​and ​definitions ​<fo:inline color="rgb(255, 0, 0)"><fo:basic-link fox:alt-text="" internal-destination="">&lt;1&gt;</fo:basic-link></fo:inline> ​
```

To do: if there isn't destination for `callout`, then omit `<fo:basic-link`.

**Comment by Intelligent2013** [comment]
The issue from the initial post:
```
[mn2pdf] Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1197:537)
[mn2pdf] org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1197:537)
[mn2pdf] javax.xml.transform.TransformerException: org.apache.fop.fo.ValidationException: Missing attribute on fo:basic-link: Either external-destination or internal-destination must be specified. (See position 1197:537)
[mn2pdf] 	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:502)
```
fixed.

**Comment by Intelligent2013** [comment]
The issue:
```
Can't flat IF.
java.lang.NumberFormatException: For input string: "50%"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
```
in progress.

**Comment by Intelligent2013** [comment]
The issue occurs due the `svg` with the element `text`:
```
<svg xmlns="http://www.w3.org/2000/svg" contentScriptType="text/ecmascript" zoomAndPan="magnify" style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd" contentStyleType="text/css" viewBox="0 0 500 500" preserveAspectRatio="xMidYMid meet" xml:space="preserve" version="1.0">
	<g id="UrTavla">
		<circle r="250" style="fill:rgb(0, 177, 255);" cx="250" cy="250">
						</circle>
		<text x="50%" font-size="18em" y="67%" text-anchor="middle" style="fill:white" font-family="Lato" dy="20em" letter-spacing="25">I</text>
	</g>
</svg>
```
Apache IF also has own element `text` with the attributes `@x` and `@y` and FOPIFFlatHandler parser mix up them.

**Comment by Intelligent2013** [comment]
All issues fixed. PDF generates successfully now.

**Comment by ronaldtse** [comment]
@Intelligent2013 can we confirm that:
* If the target items are commented out, generation works?
* If the target items are not commented out, generation also works?

Thanks!

**Comment by Intelligent2013** [comment]
> * If the target items are commented out, generation works?

@ronaldtse yes.

> * If the target items are not commented out, generation also works?

yes. But looks like I have to add a space before target items:

![image](https://user-images.githubusercontent.com/5559926/227397943-e80a6682-5c87-42e2-a8fe-3b97b6a6cd3e.png)

**Comment by ronaldtse** [comment]
When the target items are present, they should be rendered as a definition list like a "Where, ...", and not in monospace font (it is not part of the source code).

So maybe this task is really about supporting source code block with a Key. This needs to be done in Metanorma XML proper.

<img width="821" alt="Screenshot 2023-03-24 at 9 11 33 AM" src="https://user-images.githubusercontent.com/11865/227399096-2a296033-8bd7-4639-b123-ee68c1734513.png">

**Comment by ronaldtse** [comment]
I'll move this to another task.

**Comment by Intelligent2013** [comment]
XSLT updated for space:
![image](https://user-images.githubusercontent.com/5559926/227399351-c158323b-e333-4603-aba8-c98ba1c0cde0.png)

**Comment by ronaldtse** [comment]
Thank you @Intelligent2013 , let's wait for @opoudjis in metanorma/metanorma-standoc#764 for an updated implementation.

**Comment by Intelligent2013** [comment]
Currently, PDF ISO renders so:
![image](https://user-images.githubusercontent.com/5559926/230719983-13cb587d-4539-41ed-96a5-b217d9657014.png)

To do:
- [ ] set the font-size for `dl` as `sourcecode` font-size

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/230720547-e8a9e442-9496-4d11-97cc-1ad1658e05cb.png)
