### ISSUE TITLE
Metanorma OGC compile error with SaasC (Windows)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#53]
Reported by @rggibb on Windows. The key message is the line:

```
1: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/isodoc-1.0.4/lib/isodoc/convert.rb:76:in `populate_css'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/isodoc-1.0.4/lib/isodoc/convert.rb:128:in `generate_css': undefined method `load_paths' for SassC:Module (NoMethodError)
```

On a Mac I was unable to reproduce the error. This seems to appear with any Metanorma file. Would this be related to the latest version of SassC perhaps missing the `load_paths` method?

For @CAMOBAP795 .

Full trace:

```sh
> metanorma -R iso-19170-cd-en-sections.html iso-19170-cd-en-sections.adoc
[relaton] Info: detecting backends:
[relaton] processor "relaton_gb" registered
[relaton] processor "relaton_iec" registered
[relaton] processor "relaton_ietf" registered
[relaton] processor "relaton_iso" registered
[relaton] processor "relaton_itu" registered
[relaton] processor "relaton_nist" registered
[relaton] processor "relaton_ogc" registered
ISO style: Initial section must be (content) Foreword
ISO style: Prefatory material must be followed by (clause) Scope
ISO style: Normative References must be followed by Terms and Definitions
ISO style: Document must contain at least one clause
ISO style: WARNING (Line 64): number not broken up in threes: 2018
No French Title Intro!
element "sections" not allowed yet; missing required element "preface" @ 62:11
element "p" not allowed here; expected element "clause" @ 62:28
element "p" not allowed here; expected element "clause" @ 64:47
element "p" not allowed here; expected element "clause" @ 65:47
element "p" not allowed here; expected element "clause" @ 66:47
element "p" not allowed here; expected element "clause" @ 67:47
element "p" not allowed here; expected element "clause" @ 68:47
element "p" not allowed here; expected element "clause" @ 69:47
element "sections" incomplete; missing required element "clause" @ 69:239
element "iso-standard" incomplete; missing required element "bibliography" @ 70:16
Traceback (most recent call last):
        29: from C:/tools/ruby25/bin/metanorma:23:in `<main>'
        28: from C:/tools/ruby25/bin/metanorma:23:in `load'
        27: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.7/exe/metanorma:20:in `<top (required)>'
        26: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.7/lib/metanorma/cli.rb:60:in `start'
        25: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        24: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        23: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        22: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        21: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.7/lib/metanorma/cli/command.rb:34:in `compile'
        20: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.7/lib/metanorma/cli/compiler.rb:33:in `compile'
        19: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.7/lib/metanorma/cli/compiler.rb:29:in `compile'
        18: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.7/lib/metanorma/cli/compiler.rb:41:in `compile_file'
        17: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-0.3.15/lib/metanorma/compile.rb:20:in `compile'
        16: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-0.3.15/lib/metanorma/compile.rb:183:in `process_extensions'
        15: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-0.3.15/lib/metanorma/compile.rb:183:in `each'
        14: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-0.3.15/lib/metanorma/compile.rb:192:in `block in process_extensions'
        13: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-iso-1.3.4/lib/metanorma/iso/processor.rb:32:in `output'
        12: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/isodoc-1.0.4/lib/isodoc/html_convert.rb:17:in `convert'
        11: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/isodoc-1.0.4/lib/isodoc/convert.rb:170:in `convert'
        10: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/isodoc-1.0.4/lib/isodoc/convert.rb:140:in `convert1'
         9: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/isodoc-1.0.4/lib/isodoc/function/utils.rb:30:in `noko'
         8: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/nokogiri-1.10.4-x64-mingw32/lib/nokogiri/xml/builder.rb:254:in `with'
         7: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/nokogiri-1.10.4-x64-mingw32/lib/nokogiri/xml/builder.rb:254:in `new'
         6: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/nokogiri-1.10.4-x64-mingw32/lib/nokogiri/xml/builder.rb:295:in `initialize'
         5: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/isodoc-1.0.4/lib/isodoc/convert.rb:141:in `block in convert1'
         4: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/nokogiri-1.10.4-x64-mingw32/lib/nokogiri/xml/builder.rb:377:in `method_missing'
         3: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/nokogiri-1.10.4-x64-mingw32/lib/nokogiri/xml/builder.rb:394:in `insert'
         2: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/isodoc-1.0.4/lib/isodoc/convert.rb:144:in `block (2 levels) in convert1'
         1: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/isodoc-1.0.4/lib/isodoc/convert.rb:76:in `populate_css'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/isodoc-1.0.4/lib/isodoc/convert.rb:128:in `generate_css': undefined method `load_paths' for SassC:Module (NoMethodError)
```

Metanorma version:

```sh
> metanorma version
Metanorma 0.3.15
Metanorma::Cli 1.2.7
Metanorma::Standoc 1.3.4/IsoDoc 1.0.4
Metanorma::ISO 1.3.4
Metanorma::Iec 0.0.7
Metanorma::Ietf 1.0.6
Metanorma::Gb 1.3.4
Metanorma::Csd 1.3.3
Metanorma::Csand 1.3.3
Metanorma::Csand 1.3.3
Metanorma::M3d 1.3.3
Metanorma::Acme 1.3.3
Metanorma::Unece 0.2.4
Metanorma::NIST 0.2.4
Metanorma::Ogc 0.2.4
Metanorma::ITU 0.2.6
> gem list --local

*** LOCAL GEMS ***

addressable (2.6.0)
algoliasearch (1.26.0)
asciidoctor (2.0.10, 1.5.8)
asciimath (1.0.8)
bigdecimal (default: 1.3.4)
bundler (2.0.2, 2.0.1)
camertron-eprun (1.1.1)
cldr-plurals-runtime-rb (1.0.1)
cmath (default: 1.0.0)
cnccs (0.1.3)
concurrent-ruby (1.1.5)
csv (default: 1.0.0)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.2.0)
etc (default: 1.0.0)
faraday (0.17.0)
fcntl (default: 1.0.0)
ffi (1.11.1 x64-mingw32, 1.9.25 x64-mingw32)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
gb-agencies (0.0.5)
gbbib (0.4.4)
gdbm (default: 2.0.0)
git (1.5.0)
html2doc (0.8.11, 0.8.10)
htmlentities (4.3.4)
httpclient (2.8.3)
iecbib (0.2.2)
ietfbib (0.4.6)
iev (0.2.2)
image_size (2.0.1, 2.0.0)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
iso-639 (0.2.8)
iso-bib-item (0.4.5)
isobib (0.4.4)
isodoc (1.0.4, 0.10.0, 0.9.23)
isoics (0.1.7)
json (2.2.0, default: 2.1.0)
liquid (4.0.3)
metanorma (0.3.15, 0.3.12, 0.3.11)
metanorma-acme (1.3.3, 1.2.0, 1.1.4)
metanorma-cli (1.2.7, 1.2.0, 1.1.8)
metanorma-csand (1.3.3, 1.2.0, 1.1.5)
metanorma-csd (1.3.3, 1.2.0, 1.1.4)
metanorma-gb (1.3.4, 1.2.0, 1.1.5)
metanorma-iec (0.0.7)
metanorma-ietf (1.0.6, 1.0.3, 1.0.2, 1.0.1)
metanorma-iso (1.3.4, 1.2.0, 1.1.5)
metanorma-itu (0.2.6)
metanorma-m3d (1.3.3, 1.2.0, 1.1.5)
metanorma-mpfd (0.1.10)
metanorma-nist (0.2.4, 0.1.1, 0.0.9)
metanorma-ogc (0.2.4, 0.1.0, 0.0.9)
metanorma-rsd (1.1.4)
metanorma-standoc (1.3.4, 1.2.0, 1.1.9)
metanorma-unece (0.2.4, 0.1.0, 0.0.14)
mime-types (3.2.2)
mime-types-data (3.2019.0331)
mimemagic (0.3.3)
mini_portile2 (2.4.0, 2.3.0)
minitest (5.10.3)
multipart-post (2.1.1)
net-telnet (0.1.1)
nistbib (0.1.6, 0.1.5)
nokogiri (1.10.4 x64-mingw32, 1.8.5 x64-mingw32)
openssl (default: 2.1.2)
optout (0.0.2)
power_assert (1.1.1)
psych (default: 3.0.2)
public_suffix (3.1.0, 3.0.3)
rake (12.3.2, 12.3.0)
rb-fsevent (0.10.3)
rb-inotify (0.10.0)
rdoc (default: 6.0.1)
relaton (0.5.6, 0.4.0, 0.3.4)
relaton-bib (0.3.9, 0.2.1, 0.1.5, 0.1.3)
relaton-cli (0.2.0, 0.1.10)
relaton-gb (0.6.5, 0.5.0)
relaton-iec (0.4.8, 0.3.0)
relaton-ietf (0.6.6, 0.5.2)
relaton-iev (0.1.1)
relaton-iso (0.6.7, 0.5.0)
relaton-iso-bib (0.3.9, 0.2.2)
relaton-itu (0.3.5, 0.2.0)
relaton-nist (0.3.6, 0.2.1)
relaton-ogc (0.1.2)
roman-numerals (0.3.0)
ruby-jing (0.0.1)
ruby_deep_clone (0.8.0)
rubyzip (2.0.0)
sass (3.7.4)
sass-listen (4.0.0)
sassc (2.0.1, 1.12.1)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
sterile (1.0.14)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
test-unit (3.2.7)
thor (0.20.3)
thread_safe (0.3.6)
twitter_cldr (4.4.4)
tzinfo (2.0.0)
tzinfo-data (1.2019.1)
unicode2latex (0.0.2)
uuidtools (2.1.5)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
```

**Comment by ronaldtse** [comment]
Purely for testing purposes, here's the original file:

```adoc
= Discrete Global Grid Systems Specifications
:docnumber: 19170
:tc-docnumber: ISO/TC 211 N 5025
:ref-docnumber: ISO 19170:2019
:edition: 1
:revdate: 2019-06-01
:copyright-year: 2019
:language: en
:title-intro-en: Geographic information
:title-main-en: Discrete Global Grid Systems Specifications
:title-part-en: Core Operations and Equal Area Earth Reference System
:title-intro-fr:
:title-main-fr: Système Global de Données Maillées Discrètes
:title-part-fr: Opérations de Base et Système de Référence Terrestre à Zone Égale
:doctype: international-standard
:docstage: 30
:docsubstage: 99
:draft:
:technical-committee-type: TC
:technical-committee-number: 211
:technical-committee: Geographic information / Geomantics
:subcommittee-number: 9
:subcommittee: Geomatics
:workgroup-type: WG
:workgroup-number: 9
:workgroup: Information management
:secretariat: SN
:docfile: iso-19170-cd-en-sections.adoc
:mn-document-class: iso
:mn-output-extensions: xml,html,doc,html_alt,rxl
:local-cache-only:
:data-uri-image:

include::sections-iso/00-foreword.adoc[]

:sectnums!:
```

**Comment by ronaldtse** [comment]
It is confirmed that upgrading sassc to the latest version worked by @rggibb. Thank you!

Then this is a bug for Metanorma to require a higher version of the sassc gem. @opoudjis Can you please help fix the gemspec before release tomorrow? Thanks!
