### ISSUE TITLE
Using `pdf` output extension causes crash due to `puppeteer`?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#60]
```sh
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.6.5/bin/metanorma)
RuntimeError: internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/mulgogi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-0.3.18/bin/metanorma-pdf.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
```

**Comment by opoudjis** [comment]
Cannot replicate.

**Comment by opoudjis** [comment]
... Do not report things as bugs when they are failures to engage with the code.

lib/metanorma/output/pdf.rb in metanorma gem runs Puppeteer as:

````
node_path = ENV["NODE_PATH"] || `npm root --quiet -g`.strip
node_cmd = ["node", pdfjs, file_url, output_path].join(" ")
_, error_str, status = Open3.capture3({ "NODE_PATH" => node_path }, node_cmd)
````

Without NODE_PATH set as an environment variable, you get the foregoing crash. With NODE_PATH set (as the code does), you do not.

So, 

````
node /Users/nickn/.rvm/gems/ruby-2.5.1/gems/metanorma-0.3.18/lib/metanorma/output/../../../bin/metanorma-pdf.js file:///Users/nickn/Documents/Arbeit/upwork/ribose/metanorma-ogc/a.xml.html a.pdf
````

crashes, but

````
NODE_PATH=/usr/local/lib/node_modules node /Users/nickn/.rvm/gems/ruby-2.5.1/gems/metanorma-0.3.18/lib/metanorma/output/../../../bin/metanorma-pdf.js file:///Users/nickn/Documents/Arbeit/upwork/ribose/metanorma-ogc/a.xml.html a.pdf
````

does not.

**Comment by opoudjis** [comment]
Presumably this issue is to be removed, @ronaldtse

**Comment by ronaldtse** [comment]
Yes, thanks. Closing.
