### ISSUE TITLE
(URGENT) Unable to compile documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#641]
Reported by @gbuehler

Document:
* https://gitlab.ogc.org/ogc/FORK_RBT_GPKG_Sprint/-/tree/main

```
gems/relaton-render-0.7.5/lib/relaton/render/fields/fields.rb:199:in `block in dateformat'
gems/relaton-render-0.7.5/lib/relaton/render/fields/fields.rb:197:in `each'
gems/relaton-render-0.7.5/lib/relaton/render/fields/fields.rb:197:in `dateformat'
gems/relaton-render-0.7.5/lib/relaton/render/fields/fields.rb:58:in `block in date_fields_format'
gems/relaton-render-0.7.5/lib/relaton/render/fields/fields.rb:57:in `each'
gems/relaton-render-0.7.5/lib/relaton/render/fields/fields.rb:57:in `date_fields_format'
gems/relaton-render-0.7.5/lib/relaton/render/fields/fields.rb:13:in `compound_fields_format'
gems/relaton-render-0.7.5/lib/relaton/render/general/render.rb:164:in `parse'
gems/isodoc-2.9.2/lib/isodoc/function/references.rb:36:in `pref_ref_code'
gems/isodoc-2.9.2/lib/isodoc/function/references.rb:45:in `bibitem_ref_code'
gems/isodoc-2.9.2/lib/isodoc/xref/xref_sect_gen.rb:242:in `reference_names'
gems/metanorma-ogc-2.5.3/lib/isodoc/ogc/xref.rb:77:in `reference_names'
gems/isodoc-2.9.2/lib/isodoc/xref/xref_sect_gen.rb:69:in `block in references'
```

**Comment by opoudjis** [comment]
There will be a full release Monday
